name: omniscapeEnv-3-0-0
channels:
  - conda-forge
dependencies:
  # Core Python
  - python>=3.9,<3.13

  # Required Python packages
  - pysyncrosim>=2.1.0
  - pandas>=2.0
  - numpy>=1.24
  - rasterio>=1.3
  - gdal>=3.6
